import { config, fields, singleton, collection } from '@keystatic/core';
import { createElement } from 'react';

// Storage: GitHub mode — the editor commits straight to the repo, so editing
// works from any browser (no local dev setup needed). Requires the KEYSTATIC_*
// env vars (generated by the first-run "Create GitHub App" flow).
export default config({
  storage: { kind: 'github', repo: 'balbertmd/nicks-repair-shop' },
  ui: {
    brand: { name: "Nick's Repair Shop", mark: () => createElement('img', { src: '/images/logo.png', height: 28, alt: "Nick's Repair Shop" }) },
    navigation: { 'Content': ['site', 'services', 'galleryPhotos', 'videos', 'guides'] },
  },
  singletons: {
    site: singleton({
      label: 'Site settings',
      path: 'src/content/settings/site',
      format: { data: 'json' },
      previewUrl: 'https://nicksrepairshop.com/',
      schema: {
        name: fields.text({ label: 'Business name' }),
        phone: fields.text({ label: 'Phone (display)', description: 'e.g. (609) 600-7708' }),
        phoneHref: fields.text({ label: 'Phone (dial link)', description: 'e.g. +16096007708' }),
        email: fields.text({ label: 'Email' }),
        address: fields.text({ label: 'Address' }),
        heroImage: fields.image({ label: 'Hero photo (top banner)', description: 'The big photo at the top of the home page.', directory: 'public/images/site', publicPath: '/images/site/' }),
        welcomeImage: fields.image({ label: 'Welcome photo (About section)', description: 'The photo next to the "Welcome" quote.', directory: 'public/images/site', publicPath: '/images/site/' }),
        // (hero & welcome default images live at /images/site/ — see public/images/site/)
        hours: fields.array(
          fields.object({
            day: fields.text({ label: 'Day' }),
            time: fields.text({ label: 'Hours', description: 'e.g. 9:00 AM – 5:00 PM, or Closed' }),
          }),
          { label: 'Hours', itemLabel: (p) => `${p.fields.day.value}: ${p.fields.time.value}` }
        ),
        socials: fields.array(
          fields.object({
            name: fields.text({ label: 'Name' }),
            brand: fields.text({ label: 'Brand slug', description: 'google, facebook, instagram, yelp…' }),
            icon: fields.text({ label: 'Font Awesome class', description: 'e.g. fa-brands fa-google' }),
            url: fields.url({ label: 'URL' }),
            show: fields.checkbox({ label: 'Show on site', defaultValue: true }),
          }),
          { label: 'Social links', itemLabel: (p) => p.fields.name.value }
        ),
      },
    }),
  },
  collections: {
    services: collection({
      label: 'Services',
      path: 'src/content/services/*',
      slugField: 'title',
      format: { data: 'json' },
      columns: ['title', 'duty'],
      previewUrl: 'https://nicksrepairshop.com/services/{slug}',
      schema: {
        title: fields.slug({ name: { label: 'Service title' } }),
        duty: fields.select({
          label: 'Duty type',
          options: [
            { label: 'Light-Duty (Auto)', value: 'light' },
            { label: 'Heavy-Duty (Truck & Trailer)', value: 'heavy' },
          ],
          defaultValue: 'light',
        }),
        icon: fields.text({ label: 'Icon key', description: 'mdi:… — browse icon-library.html for keys' }),
        order: fields.integer({ label: 'Sort order', defaultValue: 0 }),
        bullets: fields.array(fields.text({ label: 'Bullet' }), { label: 'Card bullets', itemLabel: (p) => p.value }),
        lead: fields.text({ label: 'Detail-page intro', multiline: true }),
        why: fields.text({ label: 'Why choose us (detail page)', multiline: true }),
        handles: fields.array(fields.text({ label: 'Item' }), { label: 'What we handle', itemLabel: (p) => p.value }),
      },
    }),
    galleryPhotos: collection({
      label: 'Gallery Photos',
      path: 'src/content/gallery/*',
      slugField: 'caption',
      format: { data: 'json' },
      columns: ['caption', 'section'],
      previewUrl: 'https://nicksrepairshop.com/#gallery',
      schema: {
        caption: fields.slug({ name: { label: 'Caption' } }),
        image: fields.image({ label: 'Photo', directory: 'public/images/gallery', publicPath: '/images/gallery/' }),
        section: fields.select({
          label: 'Which gallery',
          options: [
            { label: 'Home page', value: 'home' },
            { label: 'Engine & Performance', value: 'auto-engine' },
            { label: 'Maintenance', value: 'auto-maintenance' },
            { label: 'Body Work & Welding', value: 'body-welding' },
            { label: 'Brakes & Suspension', value: 'brakes-suspension' },
            { label: 'Chassis, Brakes & Air-Ride', value: 'chassis-brakes' },
            { label: 'Diagnostics & Inspection', value: 'diagnostics-inspection' },
            { label: 'Powertrain & Diesel', value: 'diesel-engine' },
            { label: 'DOT & Preventive Maintenance', value: 'dot-pm' },
            { label: 'Drivetrain', value: 'drivetrain' },
            { label: 'Electrical & Climate', value: 'electrical-climate' },
            { label: 'Emissions & Exhaust', value: 'emissions-exhaust' },
            { label: 'Tires & Wheels', value: 'tires-wheels' },
            { label: 'Trailer Repair', value: 'trailer-roadside' },
          ],
          defaultValue: 'home',
        }),
        order: fields.integer({ label: 'Sort order', defaultValue: 0 }),
      },
    }),
    videos: collection({
      label: 'Videos (YouTube)',
      path: 'src/content/videos/*',
      slugField: 'title',
      format: { data: 'json' },
      columns: ['title', 'section'],
      previewUrl: 'https://nicksrepairshop.com/#videos',
      schema: {
        title: fields.slug({ name: { label: 'Title' } }),
        youtube: fields.text({ label: 'YouTube link or video ID', description: 'Paste the full YouTube URL (or just the 11-character video ID)' }),
        section: fields.select({
          label: 'Which gallery',
          options: [
            { label: 'Home page', value: 'home' },
            { label: 'Engine & Performance', value: 'auto-engine' },
            { label: 'Maintenance', value: 'auto-maintenance' },
            { label: 'Body Work & Welding', value: 'body-welding' },
            { label: 'Brakes & Suspension', value: 'brakes-suspension' },
            { label: 'Chassis, Brakes & Air-Ride', value: 'chassis-brakes' },
            { label: 'Diagnostics & Inspection', value: 'diagnostics-inspection' },
            { label: 'Powertrain & Diesel', value: 'diesel-engine' },
            { label: 'DOT & Preventive Maintenance', value: 'dot-pm' },
            { label: 'Drivetrain', value: 'drivetrain' },
            { label: 'Electrical & Climate', value: 'electrical-climate' },
            { label: 'Emissions & Exhaust', value: 'emissions-exhaust' },
            { label: 'Tires & Wheels', value: 'tires-wheels' },
            { label: 'Trailer Repair', value: 'trailer-roadside' },
          ],
          defaultValue: 'home',
        }),
        order: fields.integer({ label: 'Sort order', defaultValue: 0 }),
      },
    }),
    guides: collection({
      label: 'Guides & Tips',
      path: 'src/content/guides/*',
      slugField: 'title',
      format: { contentField: 'content' },
      columns: ['title', 'date'],
      previewUrl: 'https://nicksrepairshop.com/guides/{slug}',
      entryLayout: 'content',
      schema: {
        title: fields.slug({ name: { label: 'Title' } }),
        description: fields.text({ label: 'Short description', description: 'One sentence shown in the guides list and in Google results.', multiline: true }),
        date: fields.date({ label: 'Date', defaultValue: { kind: 'today' } }),
        content: fields.markdoc({
          label: 'Article',
          extension: 'md',
          options: {
            bold: true,
            italic: true,
            heading: [2, 3],
            blockquote: true,
            orderedList: true,
            unorderedList: true,
            link: true,
            divider: true,
            image: { directory: 'public/images/guides', publicPath: '/images/guides/' },
          },
        }),
      },
    }),
  },
});
